services:
  - name: taskflow
    type: web
    env: php
    plan: free
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: TaskFlow
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: taskflow
          type: web
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: taskflow-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taskflow-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: taskflow-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taskflow-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: taskflow-db
          property: password

databases:
  - name: taskflow-db
    type: postgresql