services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:XJ+YAwf6J3Rx2eVgLcNpDPHeju0BRDdY2pYqHot6Tsk=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: bsqrs5wed3rwmdwjg61m-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: bsqrs5wed3rwmdwjg61m
      - key: DB_USERNAME
        value: u2aibspxoug2uteb
      - key: DB_PASSWORD
        value: 4uHY12EWLrauub28splj